// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mscyoiqyhbfaxzokxtou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zY3lvaXF5aGJmYXh6b2t4dG91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MDczMTgsImV4cCI6MjA2MjM4MzMxOH0.ocUCeBs-1On98Nm01LOK-FUX2I8pRbvS7CvqUlT5P6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);